# Generated by Django 5.0.7 on 2024-08-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_delete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='slug'),
        ),
    ]
