# Generated by Django 5.0.7 on 2024-08-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_index', models.CharField(max_length=20, verbose_name='Версия')),
                ('version_name', models.CharField(max_length=150, verbose_name='Название')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуально')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Продукт', to='main.product')),
            ],
            options={
                'verbose_name': 'Версия',
                'verbose_name_plural': 'Версии',
            },
        ),
    ]
