# Generated by Django 5.0.7 on 2024-09-10 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_actual",
            field=models.BooleanField(default=True, verbose_name="Актуальная версия"),
        ),
        migrations.AlterField(
            model_name="version",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="version",
                to="main.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_index",
            field=models.CharField(max_length=20, verbose_name="Номер версии"),
        ),
    ]
