# Generated by Django 4.2 on 2024-09-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_publicate_product", "Can publicate product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
